<?php
/*======================================================================*\
|| #################################################################### ||
|| # Package - Joomla Template based on YJSimpleGrid Framework          ||
|| # Copyright (C) 2010  Youjoomla.com. All Rights Reserved.            ||
|| # license - PHP files are licensed under  GNU/GPL V2                 ||
|| # license - CSS  - JS - IMAGE files  are Copyrighted material        ||
|| # bound by Proprietary License of Youjoomla.com                      ||
|| # for more information visit http://www.youjoomla.com/license.html   ||
|| # Redistribution and  modification of this software                  ||
|| # is bounded by its licenses                                         ||
|| # websites - http://www.youjoomla.com | http://www.yjsimplegrid.com  ||
|| #################################################################### ||
\*======================================================================*/
defined( '_JEXEC' ) or die( 'Restricted index access' );
/*  
  !!! DO NOT EDIT THIS FILE. IT MIGHT BE CHANGED ON UPDATE
  this file is custom for this template only. if you wish to edit or add 
  own code to the template, use template_name/custom/yjsg_custom_params.php
  
*/
/*

	this variable is for custom link color. you can use it to style any HTML elements
	see instructions here:
	http://www.yjsimplegrid.com/documentation/advanced/elements-styling-based-on-link-color.html

*/
	
$cc_css ="a{color:".$style_color.";}";
$pie_add_more =',.mycircle,.mycirclehold,.btn,.inputbox,#topmenu_holder.yjsgmega,#topmenu_holder.topmodpoz,#topmenu_holder.topmodpoz_navbar,.rm_content,.trialLink a,.yjsg4_before, ';
/* K2 CSS */
	//$document->addScript('http://tympanus.net/Tutorials/CircleHoverEffects/js/modernizr.custom.79639.js');
$topMenuLocation 	 =1; // 1 = inside the header block next to logo

//-- TOP MENU VERTICAL OFFSET --
//top menu top offsets | if empty top offset is 30 otherwise top offset is what you set here --
$DDverticalTopOffset =30;// SmoothDropdown


/*JS IMAGE EFFECT */
$YjsgCustomJS	= array();
$YjsgCustomJS[] = $yj_site.'/src/styles.js';




$yjsg3_before	= '<div class="yjsg3_before">';
$yjsg3_after	='</div>';
$yjsg4_before	= '<div class="yjsg4_before">';
$yjsg4_after	='</div>';
$yjsg5_before	= '<div class="yjsg5_before">';
$yjsg5_after	='</div>';
$yjsg6_before	= '<div class="yjsg6_before">';
$yjsg6_after	='</div>';
$yjsg7_before	= '<div class="yjsg7_before">';
$yjsg7_after	='</div>';
$footer_before 	= '<div class="footer_holders footer">';
$footer_after  	= '</div>';


?>